<div id="shippingInfo" class="centerColumn border_style">
<style>
.title_style { margin-left:10px; padding-bottom:10px; border-bottom:1px solid #CECECE;}
.table_style {border-collapse:collapse; border:1px solid #FF6600;}
.table_style td { padding:5px 10px;border:1px solid #FF6600;}
.border_style { border:1px solid #FF6600;margin-left:10px; padding:10px; padding-left:0; line-height:14px;}
</style>
<h1 id="shippingInfoHeading" class="title_style">Terms of Use</h1>

<div id="shippingInfoMainContent" class="content">
<!-- 11111111111111111111111111 -->
<p> (the &quot;Site&quot;) of <?php echo HTTP_SERVER;?>.  <?php echo HTTP_SERVER;?> provides its services to you subject to the notices, terms, and conditions set forth in this agreement (the “Agreement”). In addition, when you use any <?php echo HTTP_SERVER;?> service (e.g., Customer Reviews), you will be subject to the rules, guidelines, policies, terms, and conditions applicable to such services, and they are incorporated into this Agreement by this reference. <?php echo HTTP_SERVER;?> reserves the right to change this Site and these terms and conditions at any time.</p>
<p>Accessing, browsing, or otherwise using the site indicates your agreement to all the terms and conditions in this agreement, so please read this agreement carefully before proceeding.</p>
<br />
<p><strong>Use of Site</strong></p>
<p>You represent and warrant that you are at least 18 years old or visiting the Site under the supervision of a parent or guardian. Subject to the terms and conditions of this Agreement, <?php echo HTTP_SERVER;?> hereby grants you a limited, revocable, non-transferable, and non-exclusive license to access and use the Site by displaying it on your Internet browser only for the purpose of shopping for personal items sold on the Site and not for any commercial use or use on behalf of any third party, except as explicitly permitted by <?php echo HTTP_SERVER;?> in advance. Any breach of this Agreement shall result in the immediate revocation of the license granted in this paragraph without notice to you.<br />
Except as permitted in the paragraph above, you may not reproduce, distribute, display, sell, lease, transmit, create derivative works from, translate, modify, reverse-engineer, disassemble, decompile, or otherwise exploit this Site or any 
portion of it unless expressly permitted by <?php echo HTTP_SERVER;?> in writing. You may not make any commercial use of any of the information provided on the Site or make any use of the Site for the benefit of another business unless explicitly permitted by <?php echo HTTP_SERVER;?> in advance. <?php echo HTTP_SERVER;?> reserves the right to refuse service, terminate accounts, and/or cancel orders in its discretion, including, without limitation, if <?php echo HTTP_SERVER;?> believes that customer conduct violates applicable laws or is harmful to <?php echo HTTP_SERVER;?>’s interests.</p>
<p><br />
  You shall not upload to, distribute, or otherwise publish through this Site any Content, information, or other material that (a)
  violates or infringes upon the copyrights, patents, trademarks, service marks, trade secrets, or other proprietary rights of any person; (b) is libelous, threatening, defamatory, obscene, indecent, pornographic, discriminatory, or could give rise to any civil or criminal liability under the laws of the U.S. or the laws of any other country that may apply; or (c) includes any bugs, viruses, worms, trap doors, Trojan horses, or other harmful code or properties. <?php echo HTTP_SERVER;?> may assign you a password and account identification to enable you to access and use certain portions of this Site. Each time you use a password or identification, you will be deemed to be authorized to access and use the Site in a manner consistent with the terms and conditions of this Agreement, and <?php echo HTTP_SERVER;?> has no obligation to investigate the authorization or source of any such access or use of the Site.  </p>
<p><br />
  You will be solely responsible for all access to and use of this site by anyone using the password and identification originally assigned to you whether or not such access to and use of this site is actually authorized by you, including without limitation, all communications and transmissions and all obligations (including without limitation financial obligations) incurred through such access or use. You are solely responsible for protecting the security and confidentiality of the password and identification assigned to you. You shall immediately notify <?php echo HTTP_SERVER;?> of any unauthorized use of your password or identification or any other breach or threatened breach of this Site's security.  </p>
<p><br />
  Aukey Limited [Company Number 7580811] with its registered office in China South City,Pinghu Town,Longgang District,Shenzhen City,Guangdong Province,P.R.China.</p>
<br />
<p><strong>Reviews and Comments</strong></p>
<p>Except as otherwise provided elsewhere in this Agreement or on the Site, anything that you submit or post to the Site and/or provide <?php echo HTTP_SERVER;?>, including, without limitation, ideas, know-how, techniques, questions, reviews, comments, and suggestions (collectively, "Submissions") is and will be treated as non-confidential and nonproprietary, and by submitting or posting, you agree to irrevocably license the entry and all IP rights related thereto (excluding the moral rights such as authorship right) to <?php echo HTTP_SERVER;?> without charge and <?php echo HTTP_SERVER;?>shall have the royalty-free, worldwide, perpetual, irrevocable, and transferable right to use, copy, distribute, display, publish, perform, sell, lease, transmit, adapt, create derivative works from such Submissions by any means and in any form, and to translate, modify, reverse-engineer, disassemble, or decompile such Submissions. All Submissions shall automatically become the sole and exclusive property of <?php echo HTTP_SERVER;?> and shall not be returned to you and you agree not to raise any dispute in connection with any use of the entry by <?php echo HTTP_SERVER;?> in the future.</p>
<p>You warrant that your Submissions, in whole or in part, are clear and free of any IP right infringement, disputes or third party claims. <?php echo HTTP_SERVER;?> assumes no liability for any misuse of copyright or any other rights of third parties by you. You undertake to defense for and indemnify the Sponsor against any losses caused due to the use of the entries for any purposes.</p>
<p>In addition to the rights applicable to any Submission, when you post comments or reviews to the Site, you also grant <?php echo HTTP_SERVER;?> the right to use the name that you submit with any review, comment, or other Content, if any, in connection with such review, comment, or other content. You represent and warrant that you own or otherwise control all of the rights to the reviews, comments, and other Content that you post on this Site and that use of your reviews, comments, or other Content by <?php echo HTTP_SERVER;?> will not infringe upon or violate the rights of any third party. You shall not use a false e-mail address, pretend to be someone other than yourself, or otherwise mislead <?php echo HTTP_SERVER;?> or third parties as to the origin of any Submissions or Content. <?php echo HTTP_SERVER;?> may, but shall not be obligated to remove or edit any Submissions (including comments or reviews) for any reason.</p>
<br />
<p><strong>Copyright</strong></p>
<p>All text, graphics, photographs or other images, button icons, audio clips, logos, slogans, trade names or word software and other contents on the website of <?php echo HTTP_SERVER;?> (collectively, "Content"), belongs exclusively to <?php echo HTTP_SERVER;?> or its appropriate content suppliers. You may not use, reproduce, copy, modify, transmit, display, publish, sell, license, publicly perform, distribute or commercially exploit any of the Content or otherwise dispose of any of the Content in a way not permitted by <?php echo HTTP_SERVER;?>, without <?php echo HTTP_SERVER;?>'s express prior written consent. The use of data mining, robots, or similar data gathering and extraction tools on <?php echo HTTP_SERVER;?> as well as the use of <?php echo HTTP_SERVER;?> trademarks or service marks in meta-tags is strictly prohibited. You may view and use the Content only for your personal information and for shopping and ordering on the Site and for no other purpose. The collection, arrangement, and assembly of all content on this Site (the "Compilation") belong exclusively <?php echo HTTP_SERVER;?>. You may not use <?php echo HTTP_SERVER;?>'s Content or Compilation in any manner that disparages or discredits <?php echo HTTP_SERVER;?> or in any way that is likely to cause confusion or violation of any applicable laws or regulations. All software used on this Site (the "Software") is the property of <?php echo HTTP_SERVER;?> and/or its Software suppliers. The Content, the Compilation and the Software are all protected under state, national and international copyright laws. All rights not expressly granted are reserved by <?php echo HTTP_SERVER;?>. Violators will be prosecuted to the full extent of the law. </p>
<br />
<p><strong>Intellectual Property Infringement Policy</strong></p>
<p>It is the policy of <?php echo HTTP_SERVER;?> to take appropriate action where necessary to uphold and recognize all relevant State, Federal and International laws in connection with material that is claimed to be infringing any trademark, copyright, patent and all or any other Intellectual Property laws. If you are an intellectual property rights owner and you believe that <?php echo HTTP_SERVER;?> sells, offers for sale, or makes available goods and/or services that infringe your intellectual property rights, then send the following information in its entirety to sales@<?php echo HTTP_SERVER;?> </p>
<p>Information required </p>
<p>1. An electronic or physical signature of the person authorized to act on behalf of the owner of an exclusive that is allegedly infringed;</p>
<p>2. A description of the allegedly infringing work or material; </p>
<p>3. A description of where the allegedly infringing material is located on the site (product(s) URL);</p>
<p>4. Information reasonably sufficient to allow us to contact you, such as your address, telephone number and e-mail address; </p>
<p>5. A statement by you that you have a good faith belief that the disputed use of the material is not authorized by the copyright or other proprietary right owner, its agent, or the law; </p>
<p>6. Identification of the intellectual property rights that you claim are infringed by the Website (e.g. "XYZ copyright", "ABC trademark, Reg. No. 123456, registered 1/1/04", etc); and </p>
<p>7. A statement by you that the above information and notification is accurate, and under penalty of perjury, that you are the copyright owner or authorized to act on behalf of the owner whose exclusive right is allegedly infringed.</p>
<br />
<p><strong>Termination and Effect of Termination</strong></p>
<p>In addition to any other legal or equitable remedies, <?php echo HTTP_SERVER;?> may, without prior notice to you, immediately terminate the Agreement or revoke any or all of your rights granted under this Agreement. Upon any termination of this Agreement, you shall immediately cease all access to and use of the Site and <?php echo HTTP_SERVER;?> shall, in addition to any other legal or equitable remedies, immediately revoke all password(s), and account identification issued to you and deny your access to and use of this Site in whole or in part. Any termination of this Agreement shall not affect the respective rights and obligations (including without limitation, payment obligations) of the parties arising before the date of termination.</p>
<br />
<p><strong>Disclaimer and Limitation of Liability</strong></p>
<p>Except as otherwise provided in the standard terms of sale that govern the same of each product on this site, this site, the products offered for sale on it and the transactions conducted through it are provided by <?php echo HTTP_SERVER;?> on an "as is" basis. <?php echo HTTP_SERVER;?> makes no prepresntations or warranties of any kind, express or implied, as to the operation of the site or the information, content, materials, or products included on this site except as provided here to the full extent permissible by applicable law,<?php echo HTTP_SERVER;?> disclaims all warranties, express or implied, including, but not limited to, implied warranties of merchantability and fitness for a particular purpose, noninfringement, title, quiet enjoyment, data accuracy, and system integration. This site may include inaccuracies, mistakes or typographical errors. <?php echo HTTP_SERVER;?> does not warrant that the content will be uninterrupted or error free. To the maximum extent permitted by law, <?php echo HTTP_SERVER;?> will not be liable for any damages of any kind arising from the use of this site, including, but not limited to, indirect, incidental, punitive, exemplary, special, or consequential damages. To the maximum extent permitted by applicable law, <?php echo HTTP_SERVER;?>'s total liability to you for any damages (regardless of the foundation for the action) shall not exceed in the aggregate the amount of fees actually paid by you to <?php echo HTTP_SERVER;?> during the month immediately preceding the act allegedly giving rise to Myefoc.com's liability.</p>
<br />

<p><strong>Order Acceptance</strong></p>
<p>Please note that the price quoted for each item on the Site should be regarded as an invitation for offer and should not be regarded as an offer. Your order is an offer for purchase, which will be accepted when <?php echo HTTP_SERVER;?> confirms your order. There may be certain orders that we are unable to accept and must cancel. <?php echo HTTP_SERVER;?> reserves the right, at its sole discretion, to refuse or cancel any order for any reason. Some situations that may result in your order being cancelled include limitations on quantities available for purchase, inaccuracies or errors in product or pricing information, or problems identified by our credit and fraud avoidance department. We may also require additional verifications or information before accepting any order. We may contact you if all or any portion of your order is cancelled or if additional information is required to accept your order.</p>
<br />
<p>Typographical Errors</p>
<p>While <?php echo HTTP_SERVER;?> strives to provide accurate product and pricing information, pricing or typographical errors may occur. <?php echo HTTP_SERVER;?> cannot confirm the price of an item until after you order. In the event that an item is listed at an incorrect price or with incorrect information due to an error in pricing or product information, <?php echo HTTP_SERVER;?> shall have the right, at our sole discretion, to refuse or cancel any orders placed for that item. In the event that an item is priced incorrectly, <?php echo HTTP_SERVER;?> may, at our discretion, either contact you for instructions or cancel your order and notify you of such cancellation.</p>
<br />
<p><strong>Arbitration</strong></p>
<p>Where the parties fail to settle dispute within 30 days after such dispute occurs, they agree to submit such a dispute to Hong Kong International Arbitration Center (the “HKIAC”) for arbitration which shall be conducted in accordance with the HKIAC arbitration rules in effect at the time of applying for arbitration. The arbitral awards are final and binding upon both parties.</p>
<br />
<p><strong>Links</strong></p>
<p>This site may contain links to other sites on the Internet that are owned and operated by third parties. You acknowledge that <?php echo HTTP_SERVER;?> is not responsible for the operation of or content located on or through any such site.</p>

<p><strong>Remedies</strong></p>
<p>You agree that <?php echo HTTP_SERVER;?>'s remedy at law for any actual or threatened breach of this Agreement would be inadequate and that <?php echo HTTP_SERVER;?> shall be entitled to specific performance or injunctive relief, or both, in addition to any damages that <?php echo HTTP_SERVER;?> may be legally entitled to recover, together with reasonable expenses of any form of dispute resolution, including, without limitation, attorneys' fees.
No right or remedy of <?php echo HTTP_SERVER;?> shall be exclusive of any other, whether at law or in equity, including, without limitation, damages injunctive relief, attorneys' fees and expenses.</p>
<p><br />
  No instance of waiver by <?php echo HTTP_SERVER;?> of its rights or remedies under these terms and conditions shall imply any obligation to grant any similar, future, or other waiver.</p>
<!-- 11111111111111111111111111 -->
</div>

<div class="buttonRow back" style="text-align:right; "><a href="http://www.<?php echo HTTP_SERVER;?>/login"><img width="64" height="23" src="http://www.<?php echo HTTP_SERVER;?>/includes/templates/blackcool/buttons/english/button_back.gif" alt="Back" title="Back"></a></div>
</div>
	
				  		      
	  <div style="padding:5px;">
<p>&nbsp;</p>
</div>
    </div> 